export const SET_LOADING = 'SET_LOADING';

export const SHOW_TOAST = 'SHOW_TOAST';

export const SET_EVENT_TYPE = 'SET_EVENT_TYPE';
export const SET_EVENT_GUESTS = 'SET_EVENT_GUESTS';
export const SET_EVENT_BUDGET = 'SET_EVENT_BUDGET';
export const SET_EVENT_DATES = 'SET_EVENT_DATES';
export const SET_EVENT_CUISINES = 'SET_EVENT_CUISINES';
export const SET_EVENT_TIMES = 'SET_EVENT_TIMES';
export const SET_EVENT_DESCRIPTION = 'SET_EVENT_DESCRIPTION';
export const SET_EVENT_DETAILS = 'SET_EVENT_DETAILS';


export const SET_USER_BASIC_DETAILS = 'SET_USER_BASIC_DETAILS'
export const SET_ORG_BASIC_DETAILS = 'SET_ORG_BASIC_DETAILS'
export const SET_USER_ABOUT_ME = 'SET_USER_ABOUT_ME'
export const SET_USER_IMAGING = 'SET_USER_IMAGING';
export const SET_LOCATION = 'SET_LOCATION';
export const STORE_PUBLIC_DATA = 'STORE_PUBLIC_DATA';
export const STORE_PRIVATE_DATA = 'STORE_PRIVATE_DATA';
export const UPDATE_IMG = 'UPDATE_IMG';
export const UPDATE_BIO = 'UPDATE_BIO';

export const SET_NOTIF = "SET_NOTIF"
export const UPDATE_USER_PRIVATE_DATA = 'UPDATE_USER_DATA';

export const SET_ORG_PUBLIC = 'SET_ORG_PUBLIC';
export const SET_ORG_PRIVATE = 'SET_ORG_PRIVATE';
export const SET_ORG_ID = 'SET_ORG_ID'

export const UPDATE_ORG_IMG = 'UPDATE_ORG_IMG';
export const UPDATE_ORG_BIO = 'UPDATE_ORG_BIO';
export const SET_ORG_NOTIF = "SET_ORG_NOTIF"
